version: '3.7'

services:
  01factory:
    stdin_open: true
    tty: true
    image: taoqf/node
    volumes:
      - ./data/01factory:/01factory
    ports: 
      - 3000:3000
    links: 
      - postgres:db
      - minio:minio

  postgres:
    image: postgres
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: 01factory
      POSTGRES_USER: 01factory
      POSTGRES_PASSWORD: 01factory
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres:db

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: 01factory
      MINIO_SECRET_KEY: 01factory
