version: "3.8"

services:
  01factory:
    image: 01factory/xxx/xxxxxx/web:latest
    build:
      context: ..
      dockerfile: ./docker/web

  db:
    image: 01factory/xxx/xxxxxx/db:latest
    build:
      context: ..
      dockerfile: ./docker/postgres
