version: "3.8"

services:
  01factory-dev:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/web:dev
    build:
      context: ..
      dockerfile: ./docker/web

  01factory-web:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/web:latest
    build:
      context: ..
      dockerfile: ./docker/web

  # postgres:
  #   image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/postgres:latest
  #   build:
  #     context: ..
  #     dockerfile: ./docker/postgres
