version: '3.8'

services:
  nginx:
    image: 114.116.19.243:6060/01factory/nginx:latest
    ports:
      - 3000:80
    depends_on:
      - 01factory-web
      - adminer
      - kkfileview
    links:
      - 01factory-web:webserver
      - adminer
      - kkfileview

  01factory-web:
    stdin_open: true
    tty: true
    image: 114.116.19.243:6060/01factory/web:latest
    volumes:
      - ./data/01factory:/01factory
      - ~/.ssh:/root/.ssh
    links:
      - postgres:db
      - minio

  01factory-doccode:
    image: 114.116.19.243:6060/01factory/doccode:latest
    volumes:
      - ./data/01factory:/01factory
    links:
      - postgres:db

  adminer:
    image: 114.116.19.243:6060/01factory/adminer:latest
    links:
      - postgres:db

  minio:
    image: 114.116.19.243:6060/01factory/minio:latest
    volumes:
      - ./data/minio:/data

  mc:
    stdin_open: true
    tty: true
    image: 114.116.19.243:6060/01factory/mc:latest
    volumes:
      - ./data/mc:/root/.mc
      - ./data/files:/01factory
    links:
      - minio

  postgres:
    image: 114.116.19.243:6060/01factory/postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql

  kkfileview:
    image: 114.116.19.243:6060/01factory/kkfileview:latest
    volumes:
      - ./data/01factory:/01factory
    links:
      - 01factory-web:webserver
