version: '3.8'

services:
  nginx:
    image: dfactory01-docker.pkg.coding.net/01factory/core/nginx:latest
    # restart: unless-stopped
    ports:
      - 3456:80
    depends_on:
      - 01factory-web
      - adminer
      - fileview
    links:
      - 01factory-web:webserver
      - adminer
      - fileview

  01factory-web:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/web:dev
    volumes:
      - ./data/01factory:/01factory
      - ~/.ssh:/root/.ssh
    links:
      - db
      - minio
      - 01factory-doccode:docode

  # 01factory-web:
  #   image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/web:latest
  #   # restart: unless-stopped
  #   volumes:
  #     - ./data/01factory:/01factory
  #   links:
  #     - db
  #     - minio
  #     - 01factory-doccode:docode

  01factory-doccode:
    image: dfactory01-docker.pkg.coding.net/01factory/core/doccode:latest
    # restart: unless-stopped
    volumes:
      - ./data/01factory:/01factory
    links:
      - db

  adminer:
    image: dfactory01-docker.pkg.coding.net/01factory/core/adminer:latest
    # restart: unless-stopped
    links:
      - db

  minio:
    image: dfactory01-docker.pkg.coding.net/01factory/core/minio:latest
    # restart: unless-stopped
    volumes:
      - ./data/minio:/data

  mc:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/01factory/core/mc:latest
    # restart: unless-stopped
    volumes:
      - ./data/mc:/root/.mc
      - ./data/files:/01factory
    links:
      - minio

  db:
    image: dfactory01-docker.pkg.coding.net/01factory/core/postgres:latest
    # restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql

  fileview:
    image: dfactory01-docker.pkg.coding.net/01factory/core/fileview:latest
    # restart: unless-stopped
    volumes:
      - ./data/01factory:/01factory
    links:
      - 01factory-web:webserver
