version: '3.8'

services:
  nginx:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/nginx:latest
    ports:
      - 3000:80
    depends_on:
      - 01factory-web
      - adminer
      - fileview
    links:
      - 01factory-web:webserver
      - adminer
      - fileview

  01factory-web:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/web:latest
    volumes:
      - ./data/01factory:/01factory
      - ~/.ssh:/root/.ssh
    links:
      - postgres:db
      - minio

  01factory-doccode:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/doccode:latest
    volumes:
      - ./data/01factory:/01factory
    links:
      - postgres:db

  adminer:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/adminer:latest
    links:
      - postgres:db

  minio:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/minio:latest
    volumes:
      - ./data/minio:/data

  mc:
    stdin_open: true
    tty: true
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/mc:latest
    volumes:
      - ./data/mc:/root/.mc
      - ./data/files:/01factory
    links:
      - minio

  postgres:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql

  fileview:
    image: dfactory01-docker.pkg.coding.net/xxxxxx/xxxxxx/fileview:latest
    volumes:
      - ./data/01factory:/01factory
    links:
      - 01factory-web:webserver
