---
- name: Build {{buildname}}
  hosts: localhost
  remote_user: root
  vars:
    usr: xxx
    psw: xxx
  tasks:
    - name: Login coding
      register: loginresult
      ansible.builtin.command: docker login -u {{usr}} -p {{psw}} dfactory01-docker.pkg.coding.net
      failed_when: "'Error' in loginresult.stderr"

    - name: Remove old image
      ansible.builtin.shell: docker rmi {{img}}
      failed_when: false

    - name: Build web image
      register: buildresult
      ansible.builtin.shell: docker-compose -f ../{{build_path}}/build.yml build {{conainter_name}}
      when: loginresult.stdout == "Login Succeeded"

    - name: Push images
      register: pushresult
      ansible.builtin.command: docker push {{img}}
      # when: buildresult.stdout.find('Error') != -1

    - name: Repush images
      register: repushresult
      ansible.builtin.command: docker push {{img}}
      # when: pushresult.stdout.find('Error') != -1
      failed_when: ('Error' in repushresult.stdout) or ('FAILED' in repushresult.stdout)
