---
- ansible.builtin.import_playbook: ./build.yml
- name: update {{buildname}}
  hosts: "{{host}}"
  remote_user: root
  vars:
    usr: xxx
    psw: xxx
  tasks:
    - name: Login coding
      register: loginresult
      ansible.builtin.command: docker login -u {{usr}} -p {{psw}} dfactory01-docker.pkg.coding.net
      failed_when: "'Error' in loginresult.stderr"

    - name: Pull images
      register: pullresult
      ansible.builtin.command:
        cmd: docker pull {{img}}
      when: loginresult.stdout == "Login Succeeded"

    - name: Repull images
      register: repullresult
      ansible.builtin.command:
        cmd: docker pull {{img}}
      when: pullresult.stdout.find('Error') != -1
      failed_when: ('Error' in repullresult.stderr) or ('FAILED' in repullresult.stderr) or ('Error' in repullresult.stdout) or ('FAILED' in repullresult.stdout)

    - name: Restart web containers
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: "{{ container_path }}"
      when: pullresult.stdout.find('Error') == -1 or repullresult.stdout.find('Error') == -1
