openapi: 3.0.3

info:
  version: 1.1.0
  title: API文档
  description: xxx系统API
  license:
    name: MIT
    url: https://dfactory01.github.io/license
  contact:
    name: taoqf
    email: tao_qiufeng@126.com

servers:
  - url: /signup/api
    description: xxx系统
  - url: http://127.0.0.1:3456/signup/api
    description: testxxx系统

tags:
  - name: 01factory
    description: 01微工厂
    externalDocs:
      description: "查看更多"
      url: https://dfactory01.github.io

components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    errorResponse:
      $ref: ./error.yml

    Error:
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int32
        error:
          type: string
        path:
          type: string
    defaultConfig:
      type: object
      required:
        - welcome_message
        - calendar_permissions
        - b_show_on_main_calendar
        - event_reminder_minutes
        - task_complete_statistics
      properties:
        sync_method:
          type: string
          description: 同步方法, 可选字段, enum(lark_cloud_table,interface, third_party_product), 可以传枚举索引(int)或者值(string)
        sync_frequency:
          type: string
          description: 同步频率, 可选字段, enum(real_time, cron), 可以传枚举索引(int)或者值(string)
        welcome_message:
          type: string
          description: 入群欢迎语, 最长2047字符
        calendar_permissions:
          type: string
          description: 日历公开范围, enum(private, public, show_only_free_busy), 可以传枚举索引(int)或者值(string)
        b_show_on_main_calendar:
          type: boolean
          description: 是否展示到用户主日历
        event_reminder_minutes:
          description: (摘自飞书开放平台文档) 日程提醒时间的偏移量，正数时表示在日程开始前X分钟提醒，负数时表示在日程开始后X分钟提醒 取值范围：-20160 ～ 20160
          type: array
          items:
            type: integer
            format: int32
        task_complete_statistics:
          type: string
          description: 群内任务提醒, enum(enable, disable, only_teacher_and_organizer), 可以传枚举索引(int)或者值(string)
        task_reminder_minutes:
          description: (摘自飞书开放平台文档) 相对于截止时间的提醒时间（如提前 30 分钟，截止时间后 30 分钟，则为 -30）
          type: array
          items:
            type: integer
            format: int32
        can_join_course_via_calendar:
          type: boolean
          description: 是否可以通过日程加入课程
        auto_create_chat:
          type: boolean
          description: 是否自动创建课程群聊
        advance_days:
          type: integer
          format: int32
          description: 自动创建群聊的提前时间（单位：天）
        welcome_type:
          type: string
          description: 欢迎语格式
        title:
          type: string
          description: 欢迎语标题
        text:
          type: string
          description: 欢迎语正文内容
        button_text:
          type: string
          description: 按钮文本
        button_url:
          type: string
          description: 按钮链接
        img_key:
          type: string
          description: 图片
        task_id:
          type: integer
          format: int64
          description: 任务id
        chat_reminder_days:
          type: string
          description: 群聊
        reminder_content:
          type: string
          description: 保留文本
    course:
      type: object
      required:
        - course_id
        - name
        - description
        - calendar_permissions
        - b_show_on_main_calendar
        - manager
      properties:
        course_id:
          type: string
          description: 课程 id
        name:
          type: string
          description: 课程名称
        description:
          type: string
          description: 课程描述
        calendar_permissions:
          type: string
          description: 日历公开范围, enum(private, public, show_only_free_busy), 可以传枚举索引(int)或者值(string)
        b_show_on_main_calendar:
          type: boolean
          description: 是否展示到用户主日历
        manager:
          type: array
          description: 课程管理员列表
          items:
            type: object
            properties:
              name:
                type: string
    courseConfig:
      type: object
      required:
        - welcome_message
        - calendar_permissions
        - b_show_on_main_calendar
      properties:
        welcome_message:
          type: string
          description: 入群欢迎语, 最长2047字符
        calendar_permissions:
          type: string
          description: 日历公开范围, enum(private, public, show_only_free_busy), 可以传枚举索引(int)或者值(string)
        b_show_on_main_calendar:
          type: boolean
          description: 是否展示到用户主日历
        event_reminder_minutes:
          description: (摘自飞书开放平台文档) 日程提醒时间的偏移量，正数时表示在日程开始前X分钟提醒，负数时表示在日程开始后X分钟提醒 取值范围：-20160 ～ 20160
          type: array
          items:
            type: integer
            format: int32
        can_join_course_via_calendar:
          type: boolean
          description: 是否可以通过日程加入课程
        auto_create_chat:
          type: boolean
          description: 是否自动创建群聊
        advance_days:
          type: integer
          format: int32
          description: 自动创建群聊提前时间（单位：天）
        need_survey:
          type: boolean
          description: 是否需要问卷
        survey_url:
          type: string
          description: 问卷链接
        welcome_type:
          type: string
          description: 欢迎语类型
        title:
          type: string
          description: 欢迎语标题
        text:
          type: string
          description: 欢迎语正文内容
        button_text:
          type: string
          description: 按钮文本
        button_url:
          type: string
          description: 按钮链接
        img_key:
          type: string
          description: 图片
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/task"

    courseUpdateConfig:
      type: object
      required:
        - calendar_permissions
        - b_show_on_main_calendar
      properties:
        calendar_permissions:
          type: string
          description: 日历公开范围, enum(private, public, show_only_free_busy), 可以传枚举索引(int)或者值(string)
        b_show_on_main_calendar:
          type: boolean
          description: 是否展示到用户主日历
        event_reminder_minutes:
          description: (摘自飞书开放平台文档) 日程提醒时间的偏移量，正数时表示在日程开始前X分钟提醒，负数时表示在日程开始后X分钟提醒 取值范围：-20160 ～ 20160
          type: array
          items:
            type: integer
            format: int32
        tasks:
          description: 任务列表
          type: array
          items:
            type: object
            required:
              - task_id
              - task_complete_statistics
            properties:
              task_id:
                type: integer
                format: int64
                description: 任务id
              task_complete_statistics:
                type: string
                description: 群内任务提醒, enum(enable, disable, only_teacher_and_organizer), 可以传枚举索引(int)或者值(string)
              task_reminder_minutes:
                description: (摘自飞书开放平台文档) 相对于截止时间的提醒时间（如提前 30 分钟，截止时间后 30 分钟，则为 -30）
                type: array
                items:
                  type: integer
                  format: int32
    task:
      type: object
      required:
        - task_id
        - name
        - description
        - task_complete_statistics
      properties:
        task_id:
          type: string
          description: 任务 id
        name:
          type: string
          description: 任务名称
        description:
          type: string
          description: 任务描述
        task_complete_statistics:
          type: string
          description: 群内任务提醒, enum(enable, disable, only_teacher_and_organizer), 可以传枚举索引(int)或者值(string)
        task_reminder_minutes:
          description: (摘自飞书开放平台文档) 相对于截止时间的提醒时间（如提前 30 分钟，截止时间后 30 分钟，则为 -30）
          type: array
          items:
            type: integer
            format: int32
    taskConfig:
      type: object
      required:
        - task_complete_statistics
      properties:
        task_complete_statistics:
          type: string
          description: 群内任务提醒, enum(enable, disable, only_teacher_and_organizer), 可以传枚举索引(int)或者值(string)
        task_reminder_minutes:
          description: (摘自飞书开放平台文档) 相对于截止时间的提醒时间（如提前 30 分钟，截止时间后 30 分钟，则为 -30）
          type: array
          items:
            type: integer
            format: int32
    pageInfo:
      type: object
      required:
        - page_size
        - page_num
        - total_cnt
      properties:
        page_size:
          type: integer
          format: int32
          description: 页面大小
        page_num:
          description: 页码（从0开始)
          type: integer
          format: int32
        total_cnt:
          description: 数据总数
          type: integer
          format: int32
    courseListConfig:
      type: object
      required:
        - welcome_message
        - calendar_permissions
        - b_show_on_main_calendar
        - event_reminder_minutes
        - task_complete_statistics
      properties:
        welcome_message:
          type: string
          description: 入群欢迎语, 最长2047字符
        calendar_permissions:
          type: string
          description: 日历公开范围, enum(private, public, show_only_free_busy), 可以传枚举索引(int)或者值(string)
        b_show_on_main_calendar:
          type: boolean
          description: 是否展示到用户主日历
        event_reminder_minutes:
          description: (摘自飞书开放平台文档) 日程提醒时间的偏移量，正数时表示在日程开始前X分钟提醒，负数时表示在日程开始后X分钟提醒 取值范围：-20160 ～ 20160
          type: array
          items:
            type: integer
            format: int32
        task_complete_statistics:
          type: string
          description: 群内任务提醒, enum(enable, disable, only_teacher_and_organizer), 可以传枚举索引(int)或者值(string)
        task_reminder_minutes:
          description: (摘自飞书开放平台文档) 相对于截止时间的提醒时间（如提前 30 分钟，截止时间后 30 分钟，则为 -30）
          type: array
          items:
            type: integer
            format: int32

paths:
  /file/{id}:
    $ref: ./file/[id].yml
  /file/upload:
    $ref: ./file/upload.yml
  /file/preview/{id}:
    $ref: ./file/preview/[id].yml
  /file/preview/imgs/{ids}:
    $ref: ./file/preview/imgs/[ids].yml
  /file/delete/{id}:
    $ref: ./file/delete/[id].yml
  /account/signin:
    $ref: ./account/signin.yml
  /doccode:
    $ref: ./doccode.yml
