openapi: 3.0.3

info:
  version: 1.1.0
  title: API文档
  description: xxx系统API
  license:
    name: MIT
    url: https://dfactory01.github.io/license
  contact:
    name: taoqf
    email: tao_qiufeng@126.com

servers:
  - url: /01factory/api
    description: xxx系统
  - url: http://127.0.0.1:3456/01factory/api
    description: testxxx系统

tags:
  - name: 01factory
    description: 01微工厂
    externalDocs:
      description: "查看更多"
      url: https://dfactory01.github.io

paths:
  /file/{id}:
    $ref: ./file/[id].yml
  /file/upload:
    $ref: ./file/upload.yml
  /file/preview/{id}:
    $ref: ./file/preview/[id].yml
  /file/preview/imgs/{ids}:
    $ref: ./file/preview/imgs/[ids].yml
  /file/delete/{id}:
    $ref: ./file/delete/[id].yml
  /doccode:
    $ref: ./doccode.yml
